//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RobotArmUR2.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float PaperPoint0X {
            get {
                return ((float)(this["PaperPoint0X"]));
            }
            set {
                this["PaperPoint0X"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float PaperPoint0Y {
            get {
                return ((float)(this["PaperPoint0Y"]));
            }
            set {
                this["PaperPoint0Y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float PaperPoint1X {
            get {
                return ((float)(this["PaperPoint1X"]));
            }
            set {
                this["PaperPoint1X"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float PaperPoint1Y {
            get {
                return ((float)(this["PaperPoint1Y"]));
            }
            set {
                this["PaperPoint1Y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float PaperPoint2X {
            get {
                return ((float)(this["PaperPoint2X"]));
            }
            set {
                this["PaperPoint2X"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float PaperPoint2Y {
            get {
                return ((float)(this["PaperPoint2Y"]));
            }
            set {
                this["PaperPoint2Y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float PaperPoint3X {
            get {
                return ((float)(this["PaperPoint3X"]));
            }
            set {
                this["PaperPoint3X"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float PaperPoint3Y {
            get {
                return ((float)(this["PaperPoint3Y"]));
            }
            set {
                this["PaperPoint3Y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("54.6375")]
        public float BLRobotRotation {
            get {
                return ((float)(this["BLRobotRotation"]));
            }
            set {
                this["BLRobotRotation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("241.38356")]
        public float BLRobotDistance {
            get {
                return ((float)(this["BLRobotDistance"]));
            }
            set {
                this["BLRobotDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("71.301")]
        public float TLRobotRotation {
            get {
                return ((float)(this["TLRobotRotation"]));
            }
            set {
                this["TLRobotRotation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("435.7497")]
        public float TLRobotDistance {
            get {
                return ((float)(this["TLRobotDistance"]));
            }
            set {
                this["TLRobotDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("108.699")]
        public float TRRobotRotation {
            get {
                return ((float)(this["TRRobotRotation"]));
            }
            set {
                this["TRRobotRotation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("435.7497")]
        public float TRRobotDistance {
            get {
                return ((float)(this["TRRobotDistance"]));
            }
            set {
                this["TRRobotDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("125.362")]
        public float BRRobotRotation {
            get {
                return ((float)(this["BRRobotRotation"]));
            }
            set {
                this["BRRobotRotation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("241.38356")]
        public float BRRobotDistance {
            get {
                return ((float)(this["BRRobotDistance"]));
            }
            set {
                this["BRRobotDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float LeftPileAngle {
            get {
                return ((float)(this["LeftPileAngle"]));
            }
            set {
                this["LeftPileAngle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("304.8")]
        public float LeftPileDistance {
            get {
                return ((float)(this["LeftPileDistance"]));
            }
            set {
                this["LeftPileDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("180")]
        public float RightPileAngle {
            get {
                return ((float)(this["RightPileAngle"]));
            }
            set {
                this["RightPileAngle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("304.8")]
        public string RightPileDistance {
            get {
                return ((string)(this["RightPileDistance"]));
            }
            set {
                this["RightPileDistance"] = value;
            }
        }
    }
}
