//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RobotArmUR2.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float PaperPointBLX {
            get {
                return ((float)(this["PaperPointBLX"]));
            }
            set {
                this["PaperPointBLX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float PaperPointBLY {
            get {
                return ((float)(this["PaperPointBLY"]));
            }
            set {
                this["PaperPointBLY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float PaperPointTLX {
            get {
                return ((float)(this["PaperPointTLX"]));
            }
            set {
                this["PaperPointTLX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float PaperPointTLY {
            get {
                return ((float)(this["PaperPointTLY"]));
            }
            set {
                this["PaperPointTLY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float PaperPointTRX {
            get {
                return ((float)(this["PaperPointTRX"]));
            }
            set {
                this["PaperPointTRX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float PaperPointTRY {
            get {
                return ((float)(this["PaperPointTRY"]));
            }
            set {
                this["PaperPointTRY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float PaperPointBRX {
            get {
                return ((float)(this["PaperPointBRX"]));
            }
            set {
                this["PaperPointBRX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float PaperPointBRY {
            get {
                return ((float)(this["PaperPointBRY"]));
            }
            set {
                this["PaperPointBRY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("54.6375")]
        public float BLRobotRotation {
            get {
                return ((float)(this["BLRobotRotation"]));
            }
            set {
                this["BLRobotRotation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("241.38356")]
        public float BLRobotExtension {
            get {
                return ((float)(this["BLRobotExtension"]));
            }
            set {
                this["BLRobotExtension"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("71.301")]
        public float TLRobotRotation {
            get {
                return ((float)(this["TLRobotRotation"]));
            }
            set {
                this["TLRobotRotation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("435.7497")]
        public float TLRobotExtension {
            get {
                return ((float)(this["TLRobotExtension"]));
            }
            set {
                this["TLRobotExtension"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("108.699")]
        public float TRRobotRotation {
            get {
                return ((float)(this["TRRobotRotation"]));
            }
            set {
                this["TRRobotRotation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("435.7497")]
        public float TRRobotExtension {
            get {
                return ((float)(this["TRRobotExtension"]));
            }
            set {
                this["TRRobotExtension"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("125.362")]
        public float BRRobotRotation {
            get {
                return ((float)(this["BRRobotRotation"]));
            }
            set {
                this["BRRobotRotation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("241.38356")]
        public float BRRobotExtension {
            get {
                return ((float)(this["BRRobotExtension"]));
            }
            set {
                this["BRRobotExtension"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float TriangleStackRotation {
            get {
                return ((float)(this["TriangleStackRotation"]));
            }
            set {
                this["TriangleStackRotation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("304.8")]
        public float TriangleStackExtension {
            get {
                return ((float)(this["TriangleStackExtension"]));
            }
            set {
                this["TriangleStackExtension"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("180")]
        public float SquareStackRotation {
            get {
                return ((float)(this["SquareStackRotation"]));
            }
            set {
                this["SquareStackRotation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("304.8")]
        public float SquareStackExtension {
            get {
                return ((float)(this["SquareStackExtension"]));
            }
            set {
                this["SquareStackExtension"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public byte BasePrescale {
            get {
                return ((byte)(this["BasePrescale"]));
            }
            set {
                this["BasePrescale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte CarriagePrescale {
            get {
                return ((byte)(this["CarriagePrescale"]));
            }
            set {
                this["CarriagePrescale"] = value;
            }
        }
    }
}
